### ISSUE TITLE
Esse app fica igual ao site?

### ISSUE THREAD

**Issue by joliviere** [alexrintt/anime-tv-unofficial-api#2]
A aparência desse app fica igual ao site [Anime TV](https://animetv.biz)?

**Comment by LaksCastro** [comment]
Opa, e aí. Acho parecido, mas não igual. Esse repositório é extraído [desse App](https://play.google.com/store/apps/details?id=br.com.meuanimetv&hl=en&gl=US).

**Comment by alexrintt** [comment]
fechando aqui, qualquer coisa só reabrir ou abrir uma nova issue.
